spring:
  application:
    name: HikariDemo
  jpa:
    open-in-view: ${JPA_OPEN_IN_VIEW:false}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}

management:
  endpoints:
    web:
      exposure:
        include: "*" # turn these off for prod

logging.level:
  com.zaxxer.hikari: ${HIKARI_LOG_LEVEL:TRACE}
  com.zaxxer.hikari.HikariConfig: ${HIKARI_CONFIG_LOG_LEVEL:DEBUG}
  com.yugabyte.Driver: ${YB_DRIVER_LOG_LEVEL:DEBUG} # use DEBUG for connection info